fix(mobile): add top space to modal
codeleap-uk/internal-libs-monorepo pull request #103
Opened 2023-09-19 19:45 UTC by Takkuya

https://www.notion.so/codeleap/Add-more-space-to-top-of-modal-7454bd30dce84e57a02f2593f576a022?pvs=4

2023-09-20 02:03 UTC, PSouza-10 requested changes

2023-09-20 02:03 UTC, PSouza-10 commented on packages/mobile/src/components/Modal/index.tsx
> +  const topSpacing = modalHeight > heightThreesold ? Theme.spacing.paddingTop(4) : Theme.spacing.paddingTop(0)
o padding aqui deveria vir do sistema de variants pra ficar editável, seria tipo variantStyles.topSpacing

2023-09-20 02:03 UTC, PSouza-10 commented on packages/mobile/src/components/Modal/index.tsx
> +    setModalHeight(height)
melhor chamar o props.onLayout aqui também, se não quem usar o componente vai perder a funcionalidade

2023-09-20 02:05 UTC, PSouza-10 commented on packages/mobile/src/components/Modal/index.tsx
> +  const heightThreesold = 1000
"heightThreesold" tá escrito errado também, é "heightThreshold"

2023-09-20 17:54 UTC, Takkuya commented on packages/mobile/src/components/Modal/index.tsx
> +  const topSpacing = modalHeight > heightThreesold ? Theme.spacing.paddingTop(4) : Theme.spacing.paddingTop(0)
Não entendi muito bem, seria para criar um topSpacing no stylesheet do modal? Mas ai não continuaria sendo estático o valor?

2023-09-20 18:04 UTC, Takkuya commented on packages/mobile/src/components/Modal/index.tsx
> +    setModalHeight(height)
Ai aqui eu chamaria o props.onLayout passando o event que eu recebo no onModalLayout?

2023-09-21 00:25 UTC, Gabriel-J3sus commented on packages/mobile/src/components/Modal/index.tsx
> +  const topSpacing = modalHeight > heightThreesold ? Theme.spacing.paddingTop(4) : Theme.spacing.paddingTop(0)
@Takkuya sim, mas seria possivel sobreescrever criando outras variants - tipo, se em algum momento ou dependendo do tipo de modal nós poderiamos aumentar ou diminuir o padding

2023-09-21 02:21 UTC, PSouza-10 approved these changes

2023-09-21 02:22 UTC, merged