Feature/dropzone
codeleap-uk/internal-libs-monorepo pull request #109
Opened 2023-10-04 22:03 UTC by AlvaroYmagawa

##Overview
* Add Dropzone component into web packages

##Screenshots
https://github.com/codeleap-uk/internal-libs-monorepo/assets/29637385/4bba6504-62b3-4b8b-a72b-71bc565a1cd1

2023-10-05 18:55 UTC, Gabriel-J3sus requested changes
Pelo que testei, ta muito bom o Dropzone e já tem tudo o que preciso para o Eworkflow

2023-10-05 18:55 UTC, Gabriel-J3sus commented on packages/web/src/components/Dropzone/index.tsx
> +          name={'file' as IconPlaceholder}
Esse ícone tbm poderia vir do `defaultProps`, o "x" para remover um arquivo, tbm

2023-10-05 18:55 UTC, Gabriel-J3sus commented on packages/web/src/components/Dropzone/index.tsx
> +      {isImage(file) ?
Aqui, acho que poderia tbm ter alguma forma de definir se eu quero que tenha preview ou não, mesmo sendo uma imagem

2023-10-05 18:55 UTC, Gabriel-J3sus commented on packages/web/src/components/Dropzone/index.tsx
> +      <Touchable onClick={e => {
Uma dúvida, não seria bom usar o ActionIcon aqui? 
Não sei nem se dá para usar, mas acho que é bom tentar

2023-10-06 20:39 UTC, PSouza-10 requested changes

2023-10-06 20:39 UTC, PSouza-10 commented on packages/web/src/components/Dropzone/index.tsx
> +          src={URL.createObjectURL(file)}
Isso não é ideal, esse método guarda o arquivo in memory só criando uma uri apontando pra ele aparentemente https://developer.mozilla.org/en-US/docs/Web/API/URL/createObjectURL_static#memory_management. Seria melhor ter algum tipo de cache e/ou sistema de revoke pra ele como sugere a Mozilla. Daria pra usar o path do arquivo como chave de cache, mas o problema disso seria o cara colocar um file, editar ele e depois tentar fazer upload novamente. Se tiver alguma informação que dê pra combinar nessa chave vai ser melhor. Ou, pensando melhor, se a referência do objeto file for constante entre os renders dá pra usar também

2023-10-10 17:12 UTC, PSouza-10 approved these changes
Só os conflicts aqui também, que bom que foi simples resolver o negócio da URL!

2023-10-11 22:01 UTC, merged