LocalStorage
codeleap-uk/internal-libs-monorepo pull request #110
Opened 2023-10-05 18:55 UTC by LuizFelipe16

2023-10-06 20:12 UTC, PSouza-10 requested changes

2023-10-06 20:12 UTC, PSouza-10 commented on packages/web/src/lib/localStorage.ts
> +      _setValue(initialValue)
Era bom registrar um listener aqui usando o método `listen` que citei no outro comment, pra já atualizar o estado entre os hooks.

2023-10-06 20:12 UTC, PSouza-10 commented on packages/web/src/lib/localStorage.ts
> +  public listen(
Acho que não deixei muito claro, mas a intenção do listen não era um hook, e sim uma função de susbcription. Se quiser ver um exemplo de como isso é feito dá uma olhada em https://github.com/codeleap-uk/internal-libs-monorepo/blob/93f3242527942b4d56332ef0604c70cfc3d53f84/packages/mobile/src/utils/notifications.ts#L166, lá tem um método que registra listeners pra notifications (dá pra fazer a mesma coisa aqui). 

O motivo disso é conseguir chamar esse tipo de coisa globalmente, não só dentro de componente.

Aí pode chamar esse listener em um effect como 
```
useEffect(() => {
    return LocalStorage.listen('key', (value) => {
        console.log(someDependency, value)
    })
}, [someDependency])
```

Pra manter o hook que já criou, pode só renomear ele pra algo como useLocalStorageValue

2023-10-06 20:12 UTC, PSouza-10 commented on packages/web/src/lib/localStorage.ts
> +  public listen(
Talvez vire ter um options como param do hook pra habilitar/desabilitar esse comportamento também

2023-10-18 16:28 UTC, PSouza-10 requested changes

2023-10-18 16:28 UTC, PSouza-10 commented on packages/web/src/lib/localStorage.ts
> +    const trigger = (event) => handler(key, event)
Como tem a key aqui, não era melhor o trigger já filtrar o que vem do evento e só disparar o handler quando ela bater?

2023-10-18 16:28 UTC, PSouza-10 commented on packages/web/src/lib/localStorage.ts
> +    const trigger = (event) => handler(key, event)
Por sinal poderia mandar o value parsed já também

2023-10-18 16:28 UTC, PSouza-10 commented on packages/web/src/lib/localStorage.ts
> +      return JSON.parse(value)
Aqui não deveria ser JSON.stringify ao invés de parse?

2023-10-18 16:28 UTC, PSouza-10 commented on packages/web/src/lib/localStorage.ts
> +    return JSON.stringify(value)
E aqui parse ao invés de stringify, indo puramente pelo nome das funções. 

"Serialize" é quando você tem algum valor na memória do programa que não pode ser guardado ou transmitido como texto, aí usa uma representação desse valor (no nosso caso json) pra mandar pra algum lugar. O "Parse" (ou mais formalmente "Deserialize") é o processo inverso disso

2023-10-18 16:28 UTC, PSouza-10 commented on packages/web/src/lib/localStorage.ts
> +    return storage.getItem(storageKey)
Porque não retornar o valor parsed aqui também?

2023-10-18 16:28 UTC, PSouza-10 commented on packages/web/src/lib/localStorage.ts
> +    const [_value, _setValue] = useState<S>(value)
aqui como o storage é síncrono, poderia iniciar o state com `() => this.getItem(key) ?? initialValue`

2023-10-18 16:28 UTC, PSouza-10 commented on packages/web/src/lib/localStorage.ts
> +  public use<S = any>(key: Key<T>, value: any): [S, (to: S | ((prev: S) => S)) => any] {
Ficaria mais claro com initialValue

2023-10-18 16:28 UTC, PSouza-10 commented on packages/web/src/lib/localStorage.ts
> +  public use<S = any>(key: Key<T>, value: any): [S, (to: S | ((prev: S) => S)) => any] {
E talvez devesse ser opcional, iniciar com null

2023-10-18 16:28 UTC, PSouza-10 commented on packages/web/src/lib/localStorage.ts
> +    onMount(() => {
Aqui era bom ter um options pra desabilitar o funcionamento desse onmount também, acho que nem sempre vamos querer que o valor sincronize automático

2023-10-18 16:28 UTC, PSouza-10 commented on packages/web/src/lib/localStorage.ts
> +    onMount(() => {
E não daria pra usar o `useValue` no lugar aqui?

2023-10-18 18:21 UTC, LuizFelipe16 commented on packages/web/src/lib/localStorage.ts
> +    onMount(() => {
o useValue ficou muito redundante, o listen já fazia ele todo, só que com useEffect

2023-10-18 18:23 UTC, LuizFelipe16 commented on packages/web/src/lib/localStorage.ts
> +    return storage.getItem(storageKey)
Eu pensei nisso, mas também fiquei na dúvida se retornar sempre parsed é o melhor caso, talvez um segundo parametro boolean pra esse comportamento

2023-10-19 20:44 UTC, PSouza-10 approved these changes

2023-10-19 20:44 UTC, merged