Feature - Add DatePicker
codeleap-uk/internal-libs-monorepo pull request #115
Opened 2023-10-13 21:22 UTC by filipefpaulo

Notion link: https://www.notion.so/codeleap/Date-Picker-Component-ef73034a380f4638be9fc0783f7454aa?pvs=4

![image](https://github.com/codeleap-uk/internal-libs-monorepo/assets/40044693/b483bd69-4a07-4d8e-965c-a5c09eb4d603)

2023-10-20 14:45 UTC, AlvaroYmagawa requested changes
Just some small suggestions

2023-10-20 14:45 UTC, AlvaroYmagawa commented on packages/web/src/components/DatePicker/index.tsx
> +  } = datePickerProps || {}
Just an suggestion, but for me is not totally clear that I need to set (minDate, maxDate, start Date) only inside datePickerProps, maybe this props could be accessible on the root of component too.
```
// This way
<DatePicker minDate={new Date()}  maxDate={new Date()}  starttDate={new Date()} />
```

2023-10-31 14:34 UTC, LuizFelipe16 commented on packages/web/src/components/DatePicker/index.tsx
> +    ...defaultProps,
aqui não deveria ser `...DatePicker.defaultProps`?

2023-10-31 14:39 UTC, LuizFelipe16 commented on packages/web/src/components/DatePicker/index.tsx
> +            isSelected && variantStyles['dayWrapper:selected'],
aqui seria bom também ter `variantStyles['dayWrapper:disabled']`

2023-10-31 14:50 UTC, LuizFelipe16 commented on packages/web/src/components/DatePicker/index.tsx
> +      return (
seria interessante conseguirmos sobrescrever esse componente, poderia ter uma prop chamada DayComponent que seria null por default, e antes desse return teria:
```
if (TypeGuards.isFunction(DayComponent)) {
 return <DayComponent value={value} disabled={isDisabled} selected={isSelected} variantStyles={variantStyles} 
 date={date} value={value} {...param} />
}
```

A mesma lógica pode ser aplicada pro **YearContentComponent**

2023-10-31 14:54 UTC, LuizFelipe16 commented on packages/web/src/components/DatePicker/index.tsx
> +    <View css={variantStyles.wrapper}>
Esse wrapper faz alguma diferença? se não, é o caso de só retornar o DatePicker

2023-10-31 15:29 UTC, LuizFelipe16 commented on packages/web/src/components/DatePicker/types.ts
> +  style?: any
style é um React.CSSProperties

2023-10-31 15:30 UTC, LuizFelipe16 commented on packages/web/src/components/DatePicker/types.ts
> +  styles?: DatePickerComposition
styles é um StylesOf<DatePickerComposition>

2023-10-31 15:36 UTC, LuizFelipe16 commented on packages/web/src/components/DatePicker/types.ts
> +} & Omit<TextInputProps, 'defaultValue'>
atualmente as variants que o typescript vai sugerir vão ser as do **TextInput**, mas deveriam ser as do `DatePicker`, faltou ter `ComponentVariants<typeof DatePickerPresets>` e no TextInputProps ser:
```
Omit<TextInputProps, 'defaultValue' | 'styles' | 'variants' | 'responsiveVariants'>
```

2023-10-31 16:49 UTC, LuizFelipe16 commented on packages/web/src/components/DatePicker/defaultComponents/Header.tsx
> +          text={`${month} ${year}`}
poderia ter uma prop chamada formatHeaderTitle, que recebe o date, month, year, e devolve uma string, o default seria retornar essa string ``${month} ${year}``

2023-12-08 19:01 UTC, filipefpaulo commented on packages/web/src/components/DatePicker/index.tsx
> +    <View css={variantStyles.wrapper}>
Esse wrapper serve para passar uma série de styles na forma de classNames para o datePicker

2023-12-12 19:49 UTC, AlvaroYmagawa approved these changes

2023-12-13 18:16 UTC, LuizFelipe16 approved these changes

2023-12-13 18:27 UTC, merged