Feat(web): Select
codeleap-uk/internal-libs-monorepo pull request #37
Opened 2023-05-09 15:07 UTC by devsfer1

Notion
 - https://www.notion.so/codeleap/Select-1e510110f5f741d098b6d94eb90b62ac?pvs=4
 - https://www.notion.so/codeleap/OverlaySearch-Autocomplete-3562130aca2148cc9b8158c6e4d7d188?pvs=4

2023-05-18 15:02 UTC, LuizFelipe16 commented on packages/web/src/components/Select/index.tsx
> +      ...(state.isFocused ? variantStyles['innerWrapper:focused'] : {}),
Aqui por exemplo, mas isso vale para os outros styles, a variant é `variantStyles.separatorIcon`, porém nos states de focused, error e disabled você pega a variant de `variantStyles['innerWrapper:state']`, não deveria ser `variantStyles['separatorIcon:state']`?

2023-05-18 15:04 UTC, LuizFelipe16 commented on packages/web/src/components/Select/index.tsx
> +      {label && <Text css={variantStyles.label} text={label} variants={['p2', 'marginTop:1', 'marginBottom:2']} />}
Acho que ao invés de usar variants aqui, poderia colocar esses estilos dentro do app web, no styleSheet do component, pra ficar mais flexível para outro dev alterar

2023-05-18 15:05 UTC, LuizFelipe16 commented on packages/web/src/components/Select/styles.ts
>  export type SelectComposition =
Dentro do component você também usa o state de `focused `, porém ele não está aqui no composition

2023-05-18 15:07 UTC, LuizFelipe16 commented on packages/web/src/components/Select/index.tsx
> +    <View variants={['column']}>
Talvez seria bom ter uma variant para manipular os estilos dessa view que fica por volta de tudo

2023-05-18 15:35 UTC, LuizFelipe16 commented
Ao rodar yarn build nessa branch, está alguns erros ao fazer a compilação do component Select, parece apenas ser de tipagem.

2023-05-23 20:00 UTC, devsfer1 commented on packages/web/src/components/Select/index.tsx
> +      {label && <Text css={variantStyles.label} text={label} variants={['p2', 'marginTop:1', 'marginBottom:2']} />}
done!

2023-05-23 20:00 UTC, devsfer1 commented on packages/web/src/components/Select/styles.ts
>  export type SelectComposition =
done!

2023-05-23 20:00 UTC, devsfer1 commented on packages/web/src/components/Select/index.tsx
> +      ...(state.isFocused ? variantStyles['innerWrapper:focused'] : {}),
done!

2023-05-25 18:56 UTC, Gabriel-J3sus requested changes
- Quando o input está vazio, acho que não precisa mostrar o dropdown com "No options"
![image](https://github.com/codeleap-uk/internal-libs-monorepo/assets/60709667/1438a276-5446-4f12-86d2-30614e1fe8c1)


- O dropdown poderia ter um maxHeight com um scroll estilizado
![image](https://github.com/codeleap-uk/internal-libs-monorepo/assets/60709667/ba5a800c-7881-4a10-bca6-d560b3482a78)


- Conforme a página cresce, o dropdown aumenta
![image](https://github.com/codeleap-uk/internal-libs-monorepo/assets/60709667/1edf6c25-3ef6-43c5-883d-4a0cb17a0179)


- Depois de selecionar, acho que o cursor deveria continuar no final do conteúdo, daí o proprio user iria deletando o conteúdo ao invés de reescrever
![image](https://github.com/codeleap-uk/internal-libs-monorepo/assets/60709667/1b3e3db8-184e-4dfa-beda-fa5b52b4bc08)

- Os espaçamentos não estão consistentes, a label deveria ter o mesmo espaçamento do TextInput, e as cores deveriam ser as mesmas do tema
![Untitled](https://github.com/codeleap-uk/internal-libs-monorepo/assets/60709667/05255a7f-1231-4bf5-b60d-c865031759d2)

2023-05-25 19:15 UTC, LuizFelipe16 commented
- O cursor deveria ficar como pointer assim que entra na área do input ou nas opções

https://github.com/codeleap-uk/internal-libs-monorepo/assets/62663507/eedfef63-5bf0-4f85-a391-ebd29b38dc9b

2023-05-25 19:29 UTC, devsfer1 commented
> Foi mal, era para eu ter comentado no web-template, mas não to conseguindo apagar para colocar la então fica aqui mesmo kkkk
> 
> * Quando o input está vazio, acho que não precisa mostrar o dropdown com "No options"
>   ![image](https://user-images.githubusercontent.com/60709667/241006100-1438a276-5446-4f12-86d2-30614e1fe8c1.png)
> * O dropdown poderia ter um maxHeight com um scroll estilizado
>   ![image](https://user-images.githubusercontent.com/60709667/241006239-ba5a800c-7881-4a10-bca6-d560b3482a78.png)
> * Conforme a página cresce, o dropdown aumenta
>   ![image](https://user-images.githubusercontent.com/60709667/241006437-1edf6c25-3ef6-43c5-883d-4a0cb17a0179.png)
> * Depois de selecionar, acho que o cursor deveria continuar no final do conteúdo, daí o proprio user iria deletando o conteúdo ao invés de reescrever
>   ![image](https://user-images.githubusercontent.com/60709667/241006598-1b3e3db8-184e-4dfa-beda-fa5b52b4bc08.png)
> * Os espaçamentos não estão consistentes, a label deveria ter o mesmo espaçamento do TextInput, e as cores deveriam ser as mesmas do tema
>   ![Untitled](https://user-images.githubusercontent.com/60709667/241008696-05255a7f-1231-4bf5-b60d-c865031759d2.png)

Esse espaçamento que vc apontou no ultimo print ele nao faz parte do select, é só um title apontando o tipo do select mesmo.

Sobre não precisar do "No options" isso é 100% controlável pelas props, ai vai depender da necessidade de cada aplicação, o tamanho do dropdown tbm é customizavel via styles, posso por um maxHeight como default apenas.

Vou dar uma olhada na estilizaçao pra deixar mais "padrao" com o template, valeu pelas dicas!

2023-06-05 18:05 UTC, PSouza-10 reviewed
Fora o comentário, acho que agora só faltaria adicionar/melhorar algumas coisas de usabilidade


- [x]  Conseguir passar não só icons, mas imagens também pro placeholder e noItems
- [x]  Permitir que os props default sejam setados globalmente. Em alguns componentes do mobile tem .defaultProps, talvez possa fazer do mesmo modo
- [x]  Adicionar um exemplo com o botão de options customizado
- [x]  Não sei se já tem isso então me corrija, mas precisa ter um limite de opções pra quando é multiple

2023-06-09 08:32 UTC, merged