Feat/button improvement [web]
codeleap-uk/internal-libs-monorepo pull request #77
Opened 2023-06-22 19:31 UTC by diMelo-dev

## Overview 
* This makes web button match mobile button
* https://www.notion.so/codeleap/Button-2b51cbf0d8bc41d297936bb2312fdfbf

## Screenshots

https://github.com/codeleap-uk/web-template/assets/115842979/35110e46-2d78-4796-90fc-55a9c0b04b53

2023-06-27 12:15 UTC, LuizFelipe16 commented
@diMelo-dev pode resolver esses conflitos

2023-06-27 13:55 UTC, devsfer1 requested changes

2023-06-27 13:55 UTC, devsfer1 commented on packages/web/src/components/Button/index.tsx
> +      {(!loading && isLeftIconHidden) && (
aqui é melhor voce armazenar essas duas condições em uma variável, isso deixar o código mais legível e também mais reusável, voce pode fazer assim:

`const shouldRenderLeftIcon = !loading && isLeftIconHidden;`

2023-06-27 13:55 UTC, devsfer1 commented on packages/web/src/components/Button/index.tsx
> +  const isLeftIconHidden = iconStyle?.display != 'none'
isso não está muito claro, essa variável é para checar se o lefIcon tá hidden, porem ela vai retornar "true" se o display for diferente de none, ta certo isso?

2023-06-27 13:55 UTC, devsfer1 commented on packages/web/src/components/Button/index.tsx
>      debounce = 600,
você não alterou isso nessa PR, mas o valor do debounce do Button deveria ficar em uma const como:

const `BUTTON_DEBOUNCE_TIME = 600`

isso vai deixar mais fácil de reutilizar além de deixar mais legível o código

2023-06-29 05:25 UTC, LuizFelipe16 approved these changes

2023-07-03 15:21 UTC, merged